name: publish

on:
  push:
    branches:
      - main

jobs:
  create-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Login en Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CD }}

      - name: Construir imagen Docker
        run: |
          docker build -t ghcr.io/brin29/devpulseapi:latest .
          docker push ghcr.io/brin29/devpulseapi:latest

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Instalar sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy aplicación Docker
        run: |
          sshpass -p "${{ secrets.AUTH_PASS }}" ssh -o StrictHostKeyChecking=no "${{ secrets.AUTH_SERVER }}" << EOF

            cd /root/devpulseapi/

            echo "${{ secrets.TOKEN_CD }}" | docker login ghcr.io -u brin29 --password-stdin

            docker pull ghcr.io/brin29/devpulseapi:latest

            docker stop devpulseapi || true
            docker rm devpulseapi || true

            docker run -d \
              --name devpulseapi \
              -p 3000:3000 \
              --restart always \
              --env-file .env \
              ghcr.io/brin29/devpulseapi:latest

          EOF
          
# name: publish

# on:
#   push:
#     branches: ["main"]

# jobs:
#   create-docker-image:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout del repositorio
#         uses: actions/checkout@v4

#       - name: Login en Github Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.TOKEN_CD }}

#       - name: Construir imagen Docker
#         run: |
#           docker build . --tag ghcr.io/brin29/devpulseapi:latest
#           docker push ghcr.io/brin29/devpulseapi:latest

#   deploy:
#     needs: create-docker-image
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy vía SSH
#         run: sudo apt-get install -y sshpass 

#       - name: Deploy aplicación Docker
#         run: |
#           sshpass -p ${{ secrets.AUTH_PASS }} ssh -o StrictHostKeyChecking=no ${{ secrets.AUTH_SERVER }} << EOF
#             cd /root/devpulseapi/
#             docker login ghcr.io -u brin29 -p ${{ secrets.TOKEN_CD }}
#             docker pull ghcr.io/brin29/devpulseapi:latest
#             docker stop devpulseapi || true
#             docker rm devpulseapi || true
#             docker run -d \
#               --name devpulseapi \
#               -p 3000:3000 \
#               --restart always \
#               --env-file .env \
#               ghcr.io/brin29/devpulseapi:latest
#           EOF